title: Henrique Carrasco Pagnossi
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://carrasco.rocks" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Henrique Carrasco
tagline: Game Developer
about-description: > 
  Game Developer since 2014. Currently working on a HRTech startup.
pic: avatar.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: henrique.carrasco.1@gmail.com # Add your Email address
phone: +55 11 98962 5998 # Add your Phone number
website: # carrasco.rocks # Add your website, do not add http://
linkedin: carrasco2 # Add your Linkedin handle
github: carrasco39 # Add your Github handle
twitter: '@krasuko' # Add your Twitter handle
curriculum: https://goo.gl/tbqdxW
skype: henrique.carrasco1

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

plugins_dir:
  - jekyll-feed
  - jekyll-assets
  - jekyll-youtube

livereload: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

include: [_pages]
